import { Stack, StackProps, Duration, CfnOutput } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import { RemovalPolicy } from 'aws-cdk-lib';
import * as path from 'path';
import { DeployConfig } from './config';
import { ackNag } from './nag';

interface BootstrapStackProps extends StackProps {
  readonly config: DeployConfig;
  readonly vpc: ec2.Vpc;
  readonly serviceSg: ec2.SecurityGroup;
  readonly bootstrapRepo: ecr.Repository;
  readonly cluster: ecs.ICluster;
  /** The shared ALB + HTTPS listener created by GatewayStack. */
  readonly httpsListener: elbv2.ApplicationListener;
  readonly imageTag?: string;
}

/**
 * The device-code bootstrap server (Cowork-3p config + org plugins/skills), on the same
 * Fargate cluster and behind the same internal ALB as the gateway, matched by host header.
 */
export class BootstrapStack extends Stack {
  constructor(scope: Construct, id: string, props: BootstrapStackProps) {
    super(scope, id, props);
    const { config, vpc, serviceSg, bootstrapRepo, cluster, httpsListener } = props;
    const imageTag = props.imageTag ?? 'latest';

    // Externalized bootstrap config lives in S3, so it can be edited (models, MCP servers,
    // egress) WITHOUT rebuilding/redeploying the container — the service re-reads it on a TTL.
    // Seeded from bootstrap/config/bootstrap-config.json; edit the S3 object thereafter.
    const configBucket = new s3.Bucket(this, 'ConfigBucket', {
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true, // deny non-TLS requests via aws:SecureTransport bucket policy
      versioned: true, // keep history of config edits
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });
    ackNag(configBucket,{
      id: 'AwsSolutions-S1',
      reason:
        'Server access logging adds little for a single-object private config bucket: '
        + 'no public access, versioning records every config change, and reads come only '
        + 'from the bootstrap task role via the S3 VPC endpoint.',
    });
    const CONFIG_KEY = 'bootstrap-config.json';
    new s3deploy.BucketDeployment(this, 'SeedConfig', {
      destinationBucket: configBucket,
      sources: [s3deploy.Source.asset(path.join(__dirname, '..', '..', 'bootstrap', 'config'))],
      // Seed once; later edits to the S3 object are NOT overwritten by redeploys because we
      // prune:false and the deployment only writes if the asset hash changes.
      prune: false,
    });
    // The BucketDeployment handler is a stack-scoped SINGLETON Lambda (shared by all
    // BucketDeployments in the stack), so these acks must live at stack scope — the
    // `seed` construct is not its ancestor. Its role policy (asset-bucket read +
    // config-bucket write wildcards) and runtime are owned by aws-cdk-lib and not
    // overridable here. Wildcards are scoped to exactly those two buckets.
    const cdkOwnedS3Wildcards =
      'CDK-generated by the aws-cdk-lib BucketDeployment construct (grantRead/grantWrite '
      + 'object wildcards), scoped to the CDK asset bucket and the config bucket only.';
    ackNag(this,
      {
        id: 'AwsSolutions-IAM4[Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole]',
        reason:
          'AWSLambdaBasicExecutionRole on the CDK-vended BucketDeployment singleton Lambda '
          + '(CloudWatch Logs write only); the function is owned by aws-cdk-lib.',
      },
      { id: 'AwsSolutions-IAM5[Action::s3:GetBucket*]', reason: cdkOwnedS3Wildcards },
      { id: 'AwsSolutions-IAM5[Action::s3:GetObject*]', reason: cdkOwnedS3Wildcards },
      { id: 'AwsSolutions-IAM5[Action::s3:List*]', reason: cdkOwnedS3Wildcards },
      { id: 'AwsSolutions-IAM5[Action::s3:Abort*]', reason: cdkOwnedS3Wildcards },
      { id: 'AwsSolutions-IAM5[Action::s3:DeleteObject*]', reason: cdkOwnedS3Wildcards },
      {
        id: `AwsSolutions-IAM5[Resource::arn:aws:s3:::cdk-hnb659fds-assets-${this.account}-${this.region}/*]`,
        reason: cdkOwnedS3Wildcards,
      },
      {
        id: `AwsSolutions-IAM5[Resource::<${this.getLogicalId(configBucket.node.defaultChild as s3.CfnBucket)}.Arn>/*]`,
        reason: cdkOwnedS3Wildcards,
      },
      {
        id: 'AwsSolutions-L1',
        reason:
          'The BucketDeployment handler runtime is pinned inside aws-cdk-lib; it tracks '
          + 'the newest runtime the framework supports and is not overridable here.',
      },
    );

    const taskDef = new ecs.FargateTaskDefinition(this, 'BootstrapTask', {
      cpu: 256,
      memoryLimitMiB: 512,
      runtimePlatform: {
        cpuArchitecture: ecs.CpuArchitecture.ARM64,
        operatingSystemFamily: ecs.OperatingSystemFamily.LINUX,
      },
    });

    // PKCE mode: the resource server validates the desktop app's Entra ACCESS TOKEN
    // (signature via Entra JWKS + iss + aud + exp). No shared gateway secret, no Entra client
    // secret — token validation uses only the PUBLIC JWKS + the expected audience (the desktop
    // public-client app id). So this task needs NO Secrets Manager entries at all.
    taskDef.addContainer('bootstrap', {
      image: ecs.ContainerImage.fromEcrRepository(bootstrapRepo, imageTag),
      logging: ecs.LogDrivers.awsLogs({
        streamPrefix: 'bootstrap',
        logRetention: logs.RetentionDays.ONE_MONTH,
      }),
      portMappings: [{ containerPort: 8081 }],
      environment: {
        PORT: '8081',
        // Claude apps gateway origin (unchanged). Used for inferenceGatewayBaseUrl; the app
        // authenticates to it via the gateway's own device-code login (independent of bootstrap).
        PUBLIC_ORIGIN: `https://${config.gatewayHost}`,
        // Entra token validation (resource-server). aud = the desktop PKCE public-client app id.
        ENTRA_TENANT_ID: config.entraTenantId,
        ENTRA_AUDIENCE: config.desktopClientId,
        // S3-backed config (edit without redeploy). config.js reads this on a 60s TTL.
        CONFIG_S3_URI: `s3://${configBucket.bucketName}/${CONFIG_KEY}`,
      },
    });
    // Bootstrap task reads its config object from S3. No Secrets Manager access needed in PKCE
    // mode — token validation uses the public Entra JWKS only.
    configBucket.grantRead(taskDef.taskRole);
    const grantReadReason =
      'grantRead object wildcard on the config bucket only; the task reads a single JSON '
      + 'object whose key is fixed but whose versions rotate.';
    ackNag(taskDef,
      { id: 'AwsSolutions-IAM5[Action::s3:GetBucket*]', reason: grantReadReason },
      { id: 'AwsSolutions-IAM5[Action::s3:GetObject*]', reason: grantReadReason },
      { id: 'AwsSolutions-IAM5[Action::s3:List*]', reason: grantReadReason },
      {
        id: `AwsSolutions-IAM5[Resource::<${this.getLogicalId(configBucket.node.defaultChild as s3.CfnBucket)}.Arn>/*]`,
        reason: grantReadReason,
      },
      {
        id: 'AwsSolutions-IAM5[Resource::*]',
        reason:
          'CDK-generated execution-role statement: ecr:GetAuthorizationToken (account-'
          + 'scoped, only valid on *) plus the log-group grant the awslogs driver emits.',
      },
      {
        id: 'AwsSolutions-ECS2',
        reason:
          'All environment values are non-sensitive by design (PKCE mode): public origin, '
          + 'Entra tenant/audience IDs (public identifiers), S3 config URI. The task holds '
          + 'no secrets at all — token validation uses the public Entra JWKS.',
      },
    );

    const service = new ecs.FargateService(this, 'BootstrapService', {
      cluster,
      taskDefinition: taskDef,
      desiredCount: 1,
      securityGroups: [serviceSg],
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      assignPublicIp: false,
      minHealthyPercent: 0,
      // Fail deployments fast instead of retrying a crashing task for hours.
      circuitBreaker: { rollback: true },
    });

    // PKCE mode: the bootstrap resource server serves ONLY /user/bootstrap on the gateway host.
    // No /mcp/* proxy (managed MCP servers are delivered with native cross-origin URLs and the
    // app connects to them directly) and no /org-plugins/* (network plugin delivery is not
    // available in PKCE mode — plugins ship via the filesystem). This rule must out-prioritize
    // the gateway's host rule (priority 10 in GatewayStack), so use priority 5.
    httpsListener.addTargets('BootstrapTg', {
      priority: 5,
      conditions: [
        elbv2.ListenerCondition.hostHeaders([config.gatewayHost]),
        elbv2.ListenerCondition.pathPatterns(['/user/bootstrap']),
      ],
      port: 8081,
      protocol: elbv2.ApplicationProtocol.HTTP,
      targets: [service],
      healthCheck: {
        path: '/healthz',
        healthyHttpCodes: '200',
        interval: Duration.seconds(30),
      },
      deregistrationDelay: Duration.seconds(10),
    });
    // No separate DNS record needed — the gateway host already resolves to this ALB.

    new CfnOutput(this, 'BootstrapUrl', { value: `https://${config.gatewayHost}/user/bootstrap` });
  }
}
