default_agent: claude_sdk_bedrock
agents:
  claude_sdk_bedrock:
    name: claude_sdk_bedrock
    entrypoint: /Users/prsinp/anthropic-on-aws/claude-agent-sdk-dynamic-skills-on-agentcore/claude_sdk_bedrock.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/prsinp/anthropic-on-aws/claude-agent-sdk-dynamic-skills-on-agentcore
    aws:
      execution_role: arn:aws:iam::548407783151:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-22e6a4e85c
      execution_role_auto_create: false
      account: '548407783151'
      region: us-west-2
      ecr_repository: 548407783151.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-claude_sdk_bedrock
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: claude_sdk_bedrock-8DvApi4rwO
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:548407783151:runtime/claude_sdk_bedrock-8DvApi4rwO
      agent_session_id: c09b795c-d667-4ea8-98f8-7611325a55bb
    codebuild:
      project_name: bedrock-agentcore-claude_sdk_bedrock-builder
      execution_role: arn:aws:iam::548407783151:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-22e6a4e85c
      source_bucket: bedrock-agentcore-codebuild-sources-548407783151-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
