customers = [
    {
        "id": "123456",
        "name": "Alejandro Rosalez",
        "email": "alejandro_rosalez@example.com",
        "phone": "619-555-3782",
        "username": "alejandro_rosalez",
    },
    {
        "id": "234567",
        "name": "Akua Mansa",
        "email": "akua_mansa@example.com",
        "phone": "202-555-9271",
        "username": "akua_mansa",
    },
    {
        "id": "345678",
        "name": "Ana Carolina Silva",
        "email": "anacarolina_silva@example.com",
        "phone": "808-555-6149",
        "username": "anacarolina_silva",
    },
    {
        "id": "456789",
        "name": "Arnav Desai",
        "email": "arnav_desai@example.com",
        "phone": "312-555-8204",
        "username": "arnav_desai",
    },
    {
        "id": "567890",
        "name": "Carlos Salazar",
        "email": "carlos_salazar@example.com",
        "phone": "718-555-4965",
        "username": "carlos_salazar",
    },
    {
        "id": "678901",
        "name": "Diego Ramirez",
        "email": "diego_ramirez@example.com",
        "phone": "305-555-7183",
        "username": "diego_ramirez",
    },
    {
        "id": "789012",
        "name": "Efua Owusu",
        "email": "efua_owusu@example.com",
        "phone": "903-555-2857",
        "username": "efua_owusu",
    },
    {
        "id": "890123",
        "name": "Jane Doe",
        "email": "jane_doe@example.com",
        "phone": "510-555-6320",
        "username": "jane_doe",
    },
    {
        "id": "901234",
        "name": "John Doe",
        "email": "john_doe@example.com",
        "phone": "212-555-1749",
        "username": "john_doe",
    },
    {
        "id": "012345",
        "name": "John Stiles",
        "email": "john_stiles@example.com",
        "phone": "907-555-3568",
        "username": "john_stiles",
    },
    {
        "id": "123457",
        "name": "Jorge Souza",
        "email": "jorge_souza@example.com",
        "phone": "214-555-8936",
        "username": "jorge_souza",
    },
    {
        "id": "234568",
        "name": "Kwaku Mensah",
        "email": "kwaku_mensah@example.com",
        "phone": "502-555-4217",
        "username": "kwaku_mensah",
    },
    {
        "id": "345679",
        "name": "Kwesi Manu",
        "email": "kwesi_manu@example.com",
        "phone": "603-555-7129",
        "username": "kwesi_manu",
    },
    {
        "id": "456780",
        "name": "Juan Li",
        "email": "juan_li@example.com",
        "phone": "412-555-2985",
        "username": "juan_li",
    },
    {
        "id": "567891",
        "name": "Jie Liu",
        "email": "jie_liu@example.com",
        "phone": "206-555-1674",
        "username": "jie_liu",
    },
    {
        "id": "678902",
        "name": "Márcia Oliveria",
        "email": "márcia_oliveria@example.com",
        "phone": "813-555-9530",
        "username": "márcia_oliveria",
    },
    {
        "id": "789013",
        "name": "María García",
        "email": "maría_garcia@example.com",
        "phone": "314-555-6872",
        "username": "maría_garcia",
    },
    {
        "id": "890124",
        "name": "Martha Rivera",
        "email": "martha_rivera@example.com",
        "phone": "253-555-4391",
        "username": "martha_rivera",
    },
    {
        "id": "901235",
        "name": "Mary Major",
        "email": "mary_major@example.com",
        "phone": "715-555-2608",
        "username": "mary_major",
    },
    {
        "id": "012346",
        "name": "Mateo Jackson",
        "email": "mateo_jackson@example.com",
        "phone": "409-555-8153",
        "username": "mateo_jackson",
    },
    {
        "id": "123458",
        "name": "Nikhil Jayashankar",
        "email": "nikhil_jayashankar@example.com",
        "phone": "240-555-7065",
        "username": "nikhil_jayashankar",
    },
    {
        "id": "234569",
        "name": "Nikki Wolf",
        "email": "nikki_wolf@example.com",
        "phone": "516-555-4829",
        "username": "nikki_wolf",
    },
    {
        "id": "345670",
        "name": "Pat Candella",
        "email": "pat_candella@example.com",
        "phone": "803-555-6197",
        "username": "pat_candella",
    },
    {
        "id": "456781",
        "name": "Paulo Santos",
        "email": "paulo_santos@example.com",
        "phone": "414-555-3056",
        "username": "paulo_santos",
    },
    {
        "id": "567892",
        "name": "Richard Roe",
        "email": "richard_roe@example.com",
        "phone": "919-555-1728",
        "username": "richard_roe",
    },
    {
        "id": "678903",
        "name": "Saanvi Sarkar",
        "email": "saanvi_sarkar@example.com",
        "phone": "309-555-8642",
        "username": "saanvi_sarkar",
    },
    {
        "id": "789014",
        "name": "Shirley Rodriguez",
        "email": "shirley_rodriguez@example.com",
        "phone": "702-555-4915",
        "username": "shirley_rodriguez",
    },
    {
        "id": "890125",
        "name": "Sofía Martínez",
        "email": "sofia_martinez@example.com",
        "phone": "319-555-6087",
        "username": "sofia_martinez",
    },
    {
        "id": "901236",
        "name": "Soo-jin Ki",
        "email": "soo-jin_ki@example.com",
        "phone": "612-555-2483",
        "username": "soo-jin_ki",
    },
    {
        "id": "012347",
        "name": "Terry Whitlock",
        "email": "terry_whitlock@example.com",
        "phone": "417-555-9356",
        "username": "terry_whitlock",
    },
    {
        "id": "123459",
        "name": "Xiulan Wang",
        "email": "xiulan_wang@example.com",
        "phone": "714-555-1802",
        "username": "xiulan_wang",
    },
    {
        "id": "234560",
        "name": "Wei Zhang",
        "email": "wei_zhang@example.com",
        "phone": "404-555-6531",
        "username": "wei_zhang",
    },
    {
        "id": "345671",
        "name": "Gil-dong Hong",
        "email": "gil-dong_hong@example.com",
        "phone": "850-555-7249",
        "username": "gil-dong_hong",
    },
    {
        "id": "456782",
        "name": "Ji-hoon Namgoong",
        "email": "ji-hoon_namgoong@example.com",
        "phone": "217-555-3918",
        "username": "ji-hoon_namgoong",
    },
]

orders = [
    {
        "id": "24601",
        "customer_id": "123456",
        "product": "Wireless Headphones",
        "quantity": 1,
        "price": 79.99,
        "status": "Shipped",
    },
    {
        "id": "13579",
        "customer_id": "123456",
        "product": "Smartphone Case",
        "quantity": 2,
        "price": 19.99,
        "status": "Processing",
    },
    {
        "id": "97531",
        "customer_id": "234567",
        "product": "Bluetooth Speaker",
        "quantity": 1,
        "price": 49.99,
        "status": "Shipped",
    },
    {
        "id": "86420",
        "customer_id": "345678",
        "product": "Fitness Tracker",
        "quantity": 1,
        "price": 129.99,
        "status": "Delivered",
    },
    {
        "id": "54321",
        "customer_id": "456789",
        "product": "Laptop Sleeve",
        "quantity": 3,
        "price": 24.99,
        "status": "Shipped",
    },
    {
        "id": "19283",
        "customer_id": "567890",
        "product": "Wireless Mouse",
        "quantity": 1,
        "price": 34.99,
        "status": "Processing",
    },
    {
        "id": "74651",
        "customer_id": "678901",
        "product": "Gaming Keyboard",
        "quantity": 1,
        "price": 89.99,
        "status": "Delivered",
    },
    {
        "id": "30298",
        "customer_id": "789012",
        "product": "Portable Charger",
        "quantity": 2,
        "price": 29.99,
        "status": "Shipped",
    },
    {
        "id": "47652",
        "customer_id": "890123",
        "product": "Smartwatch",
        "quantity": 1,
        "price": 199.99,
        "status": "Processing",
    },
    {
        "id": "61984",
        "customer_id": "901234",
        "product": "Noise-Cancelling Headphones",
        "quantity": 1,
        "price": 149.99,
        "status": "Shipped",
    },
    {
        "id": "58243",
        "customer_id": "012345",
        "product": "Wireless Earbuds",
        "quantity": 2,
        "price": 99.99,
        "status": "Delivered",
    },
    {
        "id": "90357",
        "customer_id": "123457",
        "product": "Smartphone Case",
        "quantity": 1,
        "price": 19.99,
        "status": "Shipped",
    },
    {
        "id": "28164",
        "customer_id": "234568",
        "product": "Wireless Headphones",
        "quantity": 2,
        "price": 79.99,
        "status": "Processing",
    },
    {
        "id": "39475",
        "customer_id": "345679",
        "product": "T-Shirt",
        "quantity": 3,
        "price": 15.99,
        "status": "Shipped",
    },
    {
        "id": "82951",
        "customer_id": "456780",
        "product": "Coffee Mug",
        "quantity": 2,
        "price": 12.99,
        "status": "Delivered",
    },
    {
        "id": "67530",
        "customer_id": "567891",
        "product": "Notebook",
        "quantity": 5,
        "price": 4.99,
        "status": "Processing",
    },
    {
        "id": "14826",
        "customer_id": "678902",
        "product": "Backpack",
        "quantity": 1,
        "price": 59.99,
        "status": "Shipped",
    },
    {
        "id": "75319",
        "customer_id": "789013",
        "product": "Water Bottle",
        "quantity": 4,
        "price": 8.99,
        "status": "Delivered",
    },
    {
        "id": "62485",
        "customer_id": "890124",
        "product": "Yoga Mat",
        "quantity": 1,
        "price": 29.99,
        "status": "Shipped",
    },
    {
        "id": "37129",
        "customer_id": "901235",
        "product": "Sunglasses",
        "quantity": 2,
        "price": 49.99,
        "status": "Processing",
    },
    {
        "id": "91753",
        "customer_id": "012346",
        "product": "Running Shoes",
        "quantity": 1,
        "price": 89.99,
        "status": "Delivered",
    },
    {
        "id": "84620",
        "customer_id": "123458",
        "product": "Hoodie",
        "quantity": 2,
        "price": 39.99,
        "status": "Shipped",
    },
    {
        "id": "59317",
        "customer_id": "234569",
        "product": "Wireless Keyboard",
        "quantity": 1,
        "price": 49.99,
        "status": "Processing",
    },
    {
        "id": "26184",
        "customer_id": "345670",
        "product": "Desk Lamp",
        "quantity": 1,
        "price": 24.99,
        "status": "Delivered",
    },
    {
        "id": "73950",
        "customer_id": "456781",
        "product": "Headphones",
        "quantity": 1,
        "price": 99.99,
        "status": "Shipped",
    },
    {
        "id": "41862",
        "customer_id": "567892",
        "product": "Smartphone Case",
        "quantity": 2,
        "price": 19.99,
        "status": "Processing",
    },
    {
        "id": "95073",
        "customer_id": "678903",
        "product": "Fitness Tracker",
        "quantity": 1,
        "price": 129.99,
        "status": "Delivered",
    },
    {
        "id": "68241",
        "customer_id": "789014",
        "product": "T-Shirt",
        "quantity": 3,
        "price": 15.99,
        "status": "Shipped",
    },
    {
        "id": "53916",
        "customer_id": "890125",
        "product": "Coffee Mug",
        "quantity": 2,
        "price": 12.99,
        "status": "Processing",
    },
    {
        "id": "79628",
        "customer_id": "901236",
        "product": "Notebook",
        "quantity": 5,
        "price": 4.99,
        "status": "Delivered",
    },
    {
        "id": "32057",
        "customer_id": "012347",
        "product": "Backpack",
        "quantity": 1,
        "price": 59.99,
        "status": "Shipped",
    },
    {
        "id": "64893",
        "customer_id": "123459",
        "product": "Water Bottle",
        "quantity": 4,
        "price": 8.99,
        "status": "Processing",
    },
    {
        "id": "87120",
        "customer_id": "234560",
        "product": "Yoga Mat",
        "quantity": 1,
        "price": 29.99,
        "status": "Delivered",
    },
    {
        "id": "19364",
        "customer_id": "345671",
        "product": "Sunglasses",
        "quantity": 2,
        "price": 49.99,
        "status": "Shipped",
    },
    {
        "id": "42857",
        "customer_id": "456782",
        "product": "Running Shoes",
        "quantity": 1,
        "price": 89.99,
        "status": "Processing",
    },
    {
        "id": "96031",
        "customer_id": "123456",
        "product": "Desk Lamp",
        "quantity": 1,
        "price": 24.99,
        "status": "Delivered",
    },
    {
        "id": "57842",
        "customer_id": "234567",
        "product": "Headphones",
        "quantity": 1,
        "price": 99.99,
        "status": "Shipped",
    },
    {
        "id": "81695",
        "customer_id": "345678",
        "product": "Wireless Keyboard",
        "quantity": 1,
        "price": 49.99,
        "status": "Processing",
    },
]
